### ISSUE TITLE
您好有两个问题

### ISSUE THREAD

**Issue by herbertchen1** [bamtercelboo/pytorch_Highway_Networks#1]
1.好像没有写控制highway lstm 堆叠层数的参数
2.model里面HBilstm_1 ,HBilstm_1等等也是模型吗？？

**Comment by herbertchen1** [comment]
HighWayBiLSTM_model 我使用这个模块就可以达到堆叠highway lstm的效果了是把

**Comment by dalinvip** [comment]
model_HBiLSTM.py
